// <auto-generated />
using DBManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DBManager.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DBManager.Models.Broker", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("APIKey")
                        .HasColumnType("text");

                    b.Property<string>("BaseURL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecretKey")
                        .HasColumnType("text");

                    b.HasKey("Name");

                    b.ToTable("Brokers");

                    b.HasData(
                        new
                        {
                            Name = "BINANCE",
                            BaseURL = "https://api.binance.com/api/v3/"
                        });
                });

            modelBuilder.Entity("DBManager.Models.Endpoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionType")
                        .HasColumnType("text");

                    b.Property<string>("BrokerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EndpointType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProtocolType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BrokerName");

                    b.ToTable("Endpoints");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActionType = "GET",
                            BrokerName = "BINANCE",
                            EndpointType = "GetCandles",
                            Path = "klines",
                            ProtocolType = "REST"
                        });
                });

            modelBuilder.Entity("DBManager.Models.Parameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BrokerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("EndpointId")
                        .HasColumnType("integer");

                    b.Property<string>("LocatedIn")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EndpointId");

                    b.HasIndex("BrokerName", "Path", "Name")
                        .IsUnique();

                    b.ToTable("Parameters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrokerName = "BINANCE",
                            LocatedIn = "query",
                            Name = "symbol",
                            Path = "klines",
                            Type = "string"
                        });
                });

            modelBuilder.Entity("DBManager.Models.Unit", b =>
                {
                    b.Property<int>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UnitId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("UnitId");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            UnitId = 1,
                            Description = "Calendar Year (365 days)",
                            Symbol = "Year",
                            UnitType = "Time"
                        },
                        new
                        {
                            UnitId = 2,
                            Description = "Calendar Month (30 days approx)",
                            Symbol = "Month",
                            UnitType = "Time"
                        },
                        new
                        {
                            UnitId = 3,
                            Description = "7 Days",
                            Symbol = "Week",
                            UnitType = "Time"
                        },
                        new
                        {
                            UnitId = 4,
                            Description = "24 Hours",
                            Symbol = "Day",
                            UnitType = "Time"
                        },
                        new
                        {
                            UnitId = 5,
                            Description = "60 Minutes",
                            Symbol = "Hour",
                            UnitType = "Time"
                        },
                        new
                        {
                            UnitId = 6,
                            Description = "60 Seconds",
                            Symbol = "Minute",
                            UnitType = "Time"
                        },
                        new
                        {
                            UnitId = 7,
                            Description = "Base Time Unit",
                            Symbol = "Second",
                            UnitType = "Time"
                        });
                });

            modelBuilder.Entity("DBManager.Models.UnitConversion", b =>
                {
                    b.Property<int>("ConversionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ConversionId"));

                    b.Property<decimal?>("FormulaOffset")
                        .HasColumnType("numeric");

                    b.Property<int>("FormulaType")
                        .HasColumnType("integer");

                    b.Property<decimal>("FormulaValue")
                        .HasColumnType("numeric");

                    b.Property<int>("FromUnitId")
                        .HasColumnType("integer");

                    b.Property<int>("ToUnitId")
                        .HasColumnType("integer");

                    b.HasKey("ConversionId");

                    b.HasIndex("FromUnitId");

                    b.HasIndex("ToUnitId");

                    b.ToTable("UnitConversions");

                    b.HasData(
                        new
                        {
                            ConversionId = 1,
                            FormulaType = 0,
                            FormulaValue = 12m,
                            FromUnitId = 1,
                            ToUnitId = 2
                        },
                        new
                        {
                            ConversionId = 2,
                            FormulaType = 0,
                            FormulaValue = 4.345m,
                            FromUnitId = 2,
                            ToUnitId = 3
                        },
                        new
                        {
                            ConversionId = 3,
                            FormulaType = 0,
                            FormulaValue = 7m,
                            FromUnitId = 3,
                            ToUnitId = 4
                        },
                        new
                        {
                            ConversionId = 4,
                            FormulaType = 0,
                            FormulaValue = 24m,
                            FromUnitId = 4,
                            ToUnitId = 5
                        },
                        new
                        {
                            ConversionId = 5,
                            FormulaType = 0,
                            FormulaValue = 60m,
                            FromUnitId = 5,
                            ToUnitId = 6
                        },
                        new
                        {
                            ConversionId = 6,
                            FormulaType = 0,
                            FormulaValue = 60m,
                            FromUnitId = 6,
                            ToUnitId = 7
                        },
                        new
                        {
                            ConversionId = 100,
                            FormulaType = 0,
                            FormulaValue = 0.0833333333333333333333333333m,
                            FromUnitId = 2,
                            ToUnitId = 1
                        },
                        new
                        {
                            ConversionId = 101,
                            FormulaType = 0,
                            FormulaValue = 0.2301495972382048331415420023m,
                            FromUnitId = 3,
                            ToUnitId = 2
                        },
                        new
                        {
                            ConversionId = 102,
                            FormulaType = 0,
                            FormulaValue = 0.1428571428571428571428571429m,
                            FromUnitId = 4,
                            ToUnitId = 3
                        },
                        new
                        {
                            ConversionId = 103,
                            FormulaType = 0,
                            FormulaValue = 0.0416666666666666666666666667m,
                            FromUnitId = 5,
                            ToUnitId = 4
                        },
                        new
                        {
                            ConversionId = 104,
                            FormulaType = 0,
                            FormulaValue = 0.0166666666666666666666666667m,
                            FromUnitId = 6,
                            ToUnitId = 5
                        },
                        new
                        {
                            ConversionId = 105,
                            FormulaType = 0,
                            FormulaValue = 0.0166666666666666666666666667m,
                            FromUnitId = 7,
                            ToUnitId = 6
                        });
                });

            modelBuilder.Entity("DBManager.Models.Endpoint", b =>
                {
                    b.HasOne("DBManager.Models.Broker", "Broker")
                        .WithMany("Endpoints")
                        .HasForeignKey("BrokerName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Broker");
                });

            modelBuilder.Entity("DBManager.Models.Parameter", b =>
                {
                    b.HasOne("DBManager.Models.Broker", "Broker")
                        .WithMany()
                        .HasForeignKey("BrokerName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBManager.Models.Endpoint", null)
                        .WithMany("Parameters")
                        .HasForeignKey("EndpointId");

                    b.Navigation("Broker");
                });

            modelBuilder.Entity("DBManager.Models.UnitConversion", b =>
                {
                    b.HasOne("DBManager.Models.Unit", "FromUnit")
                        .WithMany()
                        .HasForeignKey("FromUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBManager.Models.Unit", "ToUnit")
                        .WithMany()
                        .HasForeignKey("ToUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromUnit");

                    b.Navigation("ToUnit");
                });

            modelBuilder.Entity("DBManager.Models.Broker", b =>
                {
                    b.Navigation("Endpoints");
                });

            modelBuilder.Entity("DBManager.Models.Endpoint", b =>
                {
                    b.Navigation("Parameters");
                });
#pragma warning restore 612, 618
        }
    }
}
