// <auto-generated />
using DBManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DBManager.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DBManager.Models.Broker", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("APIKey")
                        .HasColumnType("text");

                    b.Property<string>("BaseURL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecretKey")
                        .HasColumnType("text");

                    b.HasKey("Name");

                    b.ToTable("Brokers");

                    b.HasData(
                        new
                        {
                            Name = "BINANCE",
                            BaseURL = "https://api.binance.com/api/v3/"
                        });
                });

            modelBuilder.Entity("DBManager.Models.Endpoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionType")
                        .HasColumnType("text");

                    b.Property<string>("BrokerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EndpointType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProtocolType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BrokerName");

                    b.ToTable("Endpoints");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActionType = "GET",
                            BrokerName = "BINANCE",
                            EndpointType = "GetCandles",
                            Path = "klines",
                            ProtocolType = "REST"
                        });
                });

            modelBuilder.Entity("DBManager.Models.Parameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BrokerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("EndpointId")
                        .HasColumnType("integer");

                    b.Property<string>("LocatedIn")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EndpointId");

                    b.HasIndex("BrokerName", "Path", "Name")
                        .IsUnique();

                    b.ToTable("Parameters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrokerName = "BINANCE",
                            LocatedIn = "query",
                            Name = "symbol",
                            Path = "klines",
                            Type = "string"
                        });
                });

            modelBuilder.Entity("DBManager.Models.Endpoint", b =>
                {
                    b.HasOne("DBManager.Models.Broker", "Broker")
                        .WithMany("Endpoints")
                        .HasForeignKey("BrokerName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Broker");
                });

            modelBuilder.Entity("DBManager.Models.Parameter", b =>
                {
                    b.HasOne("DBManager.Models.Broker", "Broker")
                        .WithMany()
                        .HasForeignKey("BrokerName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBManager.Models.Endpoint", null)
                        .WithMany("Parameters")
                        .HasForeignKey("EndpointId");

                    b.Navigation("Broker");
                });

            modelBuilder.Entity("DBManager.Models.Broker", b =>
                {
                    b.Navigation("Endpoints");
                });

            modelBuilder.Entity("DBManager.Models.Endpoint", b =>
                {
                    b.Navigation("Parameters");
                });
#pragma warning restore 612, 618
        }
    }
}
