"""
The lookahead-free reimplementation of 3.46's assembled rule, and the portfolio machinery used to
stress it. This is the code behind PROJECT_STATE 3.47's RETRACTION of 3.45/3.46.

Rule (fixed before the original script was written, unchanged from 3.46):
  daily close > close 20 days ago AND that move >= 2 * daily ATR(14)  -> longs only
  (mirror for shorts) -> enter on the first H4 close beyond the prior H4 bar's
  high/low; stop 1 * H4 ATR(14), target 3 * H4 ATR(14).

THE `doff` PARAMETER IS THE BUG, AND IT IS DELIBERATELY STILL REACHABLE.
`entries(..., doff=)` selects which daily bar an H4 entry consults:

    doff = -1   the still-forming daily bar   -> reads up to 20h of future (~10h mean)
    doff = -2   the last CLOSED daily bar     -> lookahead-free, and negative

3.47's finding is that the edge is a monotone function of how much future is leaked, so both
settings have to remain runnable to reproduce that table. -2 is the honest one. Do not "fix" this by
deleting -1; the comparison IS the result.

3.47 also notes why this file matters: "Unlike the 3.45/3.46 work, these are on disk - the reason
that result could not be checked is that its script was not." Which is why it is now in the repo
rather than in a scratch directory.

Data: reads long-{tag}-{h4,d1}.csv from $ALFONSO_DATA. Those are a different export from the
m15/h1/h4 set `alfonso_export_bars.py` produces and are not regenerated by it.
"""
import csv, datetime, statistics, bisect, itertools, os, sys

TAGS = ['gold', 'silver', 'nas100', 'us30', 'eurusd', 'gbpjpy']
DIR = os.environ.get('ALFONSO_DATA') or '/mnt/storage/scratch/alfonso'

# Per-instrument stop-slippage overrun, recomputed from the same 590 real Alfonso
# trades 3.45/3.46 used (lg2-small-tight gold + lg-small-tight-* others).
# Median of (|entry-exit| - |entry-stop|) / |entry-stop| over InitialStopLoss exits.
SLIP_MEDIAN = {'gold': .0596, 'silver': .0417, 'nas100': .0640,
               'us30': .1170, 'eurusd': .1825, 'gbpjpy': .1442}
SLIP_MEAN   = {'gold': .0963, 'silver': .0580, 'nas100': .1028,
               'us30': .1785, 'eurusd': .3587, 'gbpjpy': .2048}
COMMISSION_R = 0.057
HORIZON = 200


def load(tag, tf):
    rows = csv.DictReader(open(f'{DIR}/long-{tag}-{tf}.csv', encoding='utf-8-sig'))
    return [(datetime.datetime.fromisoformat(r['openTime']), float(r['open']),
             float(r['high']), float(r['low']), float(r['close'])) for r in rows]


def atr(bars, p=14):
    out = [0.0] * len(bars); run = 0.0
    for i in range(len(bars)):
        pc = bars[i - 1][4] if i else bars[0][1]
        tr = max(bars[i][2] - bars[i][3], abs(bars[i][2] - pc), abs(bars[i][3] - pc))
        run = tr if i == 0 else ((run * (p - 1)) + tr) / p
        out[i] = run
    return out


def entries(tag, doff=-2, trend_lookback=20, trend_atr_mult=2.0):
    """Every H4 bar where the rule fires. No lookahead: the daily bar consulted
    is the last one that had certainly closed before the H4 bar's open."""
    h4, d1 = load(tag, 'h4'), load(tag, 'd1')
    ah4, ad1 = atr(h4), atr(d1)
    dopen = [b[0] for b in d1]
    out = []
    for i in range(1, len(h4)):
        t = h4[i][0]
        di = bisect.bisect_left(dopen, t) + doff  # -1 = still-forming daily bar (LOOKAHEAD); -2 = last closed
        if di < trend_lookback or di >= len(d1) or ad1[di] <= 0 or ah4[i] <= 0:
            continue
        move = d1[di][4] - d1[di - trend_lookback][4]
        thresh = trend_atr_mult * ad1[di]
        if move >= thresh:      d = 1
        elif move <= -thresh:   d = -1
        else:                   continue
        # entry trigger: H4 close beyond the previous H4 bar's extreme
        if d > 0 and not h4[i][4] > h4[i - 1][2]: continue
        if d < 0 and not h4[i][4] < h4[i - 1][3]: continue
        out.append((t, tag, d, i, h4[i][4], ah4[i]))
    return out, h4


def resolve(h4, i, d, entry, unit, gap_aware, stop_mult=1.0, target_mult=3.0):
    """Walk forward. Returns (exit_time, gross_R, outcome, gapped).
    Stop is checked before target within a bar. gross_R is the *price* result in
    units of risk, before slippage/commission."""
    stop = entry - d * stop_mult * unit
    tgt = entry + d * target_mult * unit
    end = min(i + 1 + HORIZON, len(h4))
    for j in range(i + 1, end):
        t, o, hi, lo, c = h4[j]
        if gap_aware:
            # a bar that opens past a level fills there, not at the level
            if (d > 0 and o <= stop) or (d < 0 and o >= stop):
                return t, d * (o - entry) / unit, 'stop', True
            if (d > 0 and o >= tgt) or (d < 0 and o <= tgt):
                return t, d * (o - entry) / unit, 'target', True
        if (d > 0 and lo <= stop) or (d < 0 and hi >= stop):
            return t, -stop_mult, 'stop', False
        if (d > 0 and hi >= tgt) or (d < 0 and lo <= tgt):
            return t, target_mult, 'target', False
    j = end - 1
    return h4[j][0], d * (h4[j][4] - entry) / unit, 'timeout', False


def net_r(tag, gross, outcome, slip):
    """Frictions: the measured stop overrun applies to a stop exit; commission
    applies to every trade. A gap-aware stop already carries its own overrun in
    `gross`, so the modelled slippage is applied only to the touch component."""
    r = gross
    if outcome == 'stop':
        r -= slip[tag] * 1.0
    return r - COMMISSION_R


def simulate(all_entries, bars, cap, gap_aware, slip, one_per_instrument=True):
    """First-come-first-served across instruments; a candidate is dropped if the
    portfolio is full. Positions are resolved independently (no shared equity)."""
    open_until = {}          # tag -> exit time
    live = []                # list of exit times
    taken, skipped_cap, skipped_inst = [], 0, 0
    for (t, tag, d, i, price, unit) in all_entries:
        live = [x for x in live if x > t]
        if one_per_instrument and open_until.get(tag, datetime.datetime.min.replace(tzinfo=t.tzinfo)) > t:
            skipped_inst += 1; continue
        if cap is not None and len(live) >= cap:
            skipped_cap += 1; continue
        xt, gross, outcome, gapped = resolve(bars[tag], i, d, price, unit, gap_aware)
        live.append(xt); open_until[tag] = xt
        taken.append((t, tag, d, net_r(tag, gross, outcome, slip), outcome, gapped, gross))
    return taken, skipped_cap, skipped_inst


BLOCKS = [('2023 H1', '2023-01-01', '2023-07-01'), ('2023 H2', '2023-07-01', '2024-01-01'),
          ('2024 H1', '2024-01-01', '2024-07-01'), ('2024 H2', '2024-07-01', '2025-01-01'),
          ('2025 H1', '2025-01-01', '2025-07-01'), ('2025 H2', '2025-07-01', '2026-01-01'),
          ('2026 H1', '2026-01-01', '2026-07-01')]


def block_of(t):
    for name, a, b in BLOCKS:
        if datetime.datetime.fromisoformat(a + 'T00:00:00+00:00') <= t < datetime.datetime.fromisoformat(b + 'T00:00:00+00:00'):
            return name
    return None
