using System.Diagnostics;
using System.Text.Json;
using System.Text.Json.Serialization;
using Brokers.Models;
using ChartAnnotator.Engine;
using ChartAnnotator.MarketData;
using ChartAnnotator.Models;
using ChartAnnotator.Regime;
using Dashboard.Contracts;

namespace DashboardExporter;

internal static class Program
{
    private static readonly InstrumentKey Instrument = new("FX:EUR/USD");
    private static readonly BarInterval FiveMinutes = BarInterval.Minutes(5);
    private static readonly BarInterval FifteenMinutes = BarInterval.Minutes(15);
    private static readonly BarInterval OneHour = BarInterval.Hours(1);

    public static async Task Main(string[] args)
    {
        string outputPath = args.Length > 0
            ? Path.GetFullPath(args[0])
            : Path.GetFullPath(Path.Combine(
                Environment.CurrentDirectory,
                "Dashboard",
                "public",
                "data",
                "sample-replay.json"));

        var annotationOptions = new ChartAnnotationOptions
        {
            AtrPeriod = 14,
            RsiPeriod = 14,
            BollingerPeriod = 20,
            BollingerStandardDeviations = 2m,
            SwingLeftBars = 2,
            SwingRightBars = 2,
            HeavyAnalysisEveryCandles = 6,
            AtrAnalysisMinimumSamples = 15,
            BollingerWidthMinimumSamples = 15,
            EfficiencyRatioAnalysisMinimumSamples = 15,
            MarketRegime = new MarketRegimeOptions
            {
                Enabled = true,
                MinimumConfirmationBars = 2,
                MinimumPersistenceBars = 2,
                AdxCalibrationMinimumSamples = 20
            }
        };
        BarInterval[] intervals = [FiveMinutes, FifteenMinutes, OneHour];
        var aggregator = new MultiTimeframeAggregator(Instrument, intervals);
        var annotator = new ChartAnnotationEngine(annotationOptions);
        var frames = intervals.ToDictionary(
            interval => interval,
            _ => new List<ReplayFrame>());

        foreach (Candle baseCandle in CreateMarketScenario())
        {
            foreach (CandleClosedEvent candleEvent in aggregator.Apply(baseCandle))
            {
                long started = Stopwatch.GetTimestamp();
                AnalysisSnapshot snapshot = await annotator.ProcessAsync(candleEvent, runtimeContext: null);
                double elapsedMicroseconds = Stopwatch.GetElapsedTime(started).TotalMicroseconds;
                List<ReplayFrame> intervalFrames = frames[candleEvent.Interval];
                intervalFrames.Add(ReplayContractMapper.ToFrame(
                    snapshot,
                    intervalFrames.Count,
                    elapsedMicroseconds));
            }
        }

        DateTimeOffset generatedAt = frames[FiveMinutes][^1].AvailableAt;
        var export = new ReplayDataset(
            SchemaVersion: 1,
            Title: "EUR/USD annotator validation replay",
            Instrument: Instrument.Value,
            GeneratedAt: generatedAt,
            Source: "Deterministic regime-change fixture generated by DashboardExporter",
            Parameters: annotationOptions,
            Series:
            [
                CreateSeries("5m", FiveMinutes, frames[FiveMinutes]),
                CreateSeries("15m", FifteenMinutes, frames[FifteenMinutes]),
                CreateSeries("1h", OneHour, frames[OneHour])
            ]);

        string? directory = Path.GetDirectoryName(outputPath);
        if (!string.IsNullOrEmpty(directory))
        {
            Directory.CreateDirectory(directory);
        }

        await using FileStream output = File.Create(outputPath);
        await JsonSerializer.SerializeAsync(
            output,
            export,
            new JsonSerializerOptions(JsonSerializerDefaults.Web)
            {
                Converters = { new JsonStringEnumConverter() }
            });

        Console.WriteLine(
            $"Wrote {export.Series.Sum(series => series.Frames.Count)} replay frames to {outputPath}.");
    }

    private static ReplaySeries CreateSeries(
        string label,
        BarInterval interval,
        IReadOnlyList<ReplayFrame> frames) => new(
            label,
            checked((int)(interval.AddTo(DateTimeOffset.UnixEpoch) - DateTimeOffset.UnixEpoch).TotalSeconds),
            frames);

    private static IEnumerable<Candle> CreateMarketScenario()
    {
        DateTimeOffset start = new(2026, 1, 5, 0, 0, 0, TimeSpan.Zero);
        decimal previousClose = 1.08200m;

        for (int index = 0; index < 480; index++)
        {
            double regime = index switch
            {
                < 90 => index * 0.000075,
                < 175 => 0.00675 - (index - 90) * 0.000095,
                < 275 => -0.001325 + (index - 175) * 0.000012,
                < 360 => -0.000125 + (index - 275) * 0.000105,
                _ => 0.0088 - (index - 360) * 0.000045
            };
            double wave = Math.Sin(index * 0.31) * 0.00115 +
                Math.Sin(index * 0.071) * 0.00075;
            double shock = index switch
            {
                >= 207 and <= 214 => (index - 206) * 0.00062,
                >= 215 and <= 224 => (225 - index) * 0.00050,
                >= 397 and <= 403 => -(index - 396) * 0.00048,
                >= 404 and <= 411 => -(412 - index) * 0.00038,
                _ => 0d
            };
            decimal close = RoundPrice(1.082 + regime + wave + shock);
            decimal spread = RoundPrice(
                0.00028 + Math.Abs(Math.Sin(index * 0.43)) * 0.00032);
            decimal open = previousClose;
            decimal high = Math.Max(open, close) + spread;
            decimal low = Math.Min(open, close) - spread * 0.9m;
            decimal volume = Math.Round(
                850m +
                (decimal)Math.Abs(Math.Sin(index * 0.17)) * 1_100m +
                Math.Abs(close - open) * 900_000m,
                0,
                MidpointRounding.AwayFromZero);
            DateTimeOffset openTime = start.AddMinutes(index * 5);

            yield return new Candle
            {
                Instrument = Instrument,
                Interval = FiveMinutes,
                OpenTime = openTime,
                CloseTime = openTime.AddMinutes(5),
                Prices = new Ohlc(open, high, low, close),
                Volume = new MarketVolume(volume, VolumeKind.TickCount),
                IsComplete = true
            };

            previousClose = close;
        }
    }

    private static decimal RoundPrice(double value) =>
        Math.Round((decimal)value, 5, MidpointRounding.AwayFromZero);
}
