// <auto-generated />
using System;
using DBManager.Postgres;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DBManager.Postgres.Migrations
{
    [DbContext(typeof(TradingHubDbContext))]
    [Migration("20260718035342_Phase4Execution")]
    partial class Phase4Execution
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DBManager.Postgres.Config.CalibrationArtifactEntity", b =>
                {
                    b.Property<Guid>("ArtifactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("artifact_id");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("approved_at");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("text")
                        .HasColumnName("approved_by");

                    b.Property<short>("ArtifactType")
                        .HasColumnType("smallint")
                        .HasColumnName("artifact_type");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("FeatureSchemaHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("feature_schema_hash");

                    b.Property<string>("MetricsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metrics");

                    b.Property<long>("SampleCount")
                        .HasColumnType("bigint")
                        .HasColumnName("sample_count");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<string>("StorageUri")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_uri");

                    b.Property<string>("StrategyId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("strategy_id");

                    b.Property<string>("StrategyVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("strategy_version");

                    b.Property<DateTimeOffset?>("TestFrom")
                        .HasColumnType("timestamptz")
                        .HasColumnName("test_from");

                    b.Property<DateTimeOffset?>("TestTo")
                        .HasColumnType("timestamptz")
                        .HasColumnName("test_to");

                    b.Property<DateTimeOffset>("TrainingFrom")
                        .HasColumnType("timestamptz")
                        .HasColumnName("training_from");

                    b.Property<DateTimeOffset>("TrainingTo")
                        .HasColumnType("timestamptz")
                        .HasColumnName("training_to");

                    b.Property<DateTimeOffset>("ValidationFrom")
                        .HasColumnType("timestamptz")
                        .HasColumnName("validation_from");

                    b.Property<DateTimeOffset>("ValidationTo")
                        .HasColumnType("timestamptz")
                        .HasColumnName("validation_to");

                    b.HasKey("ArtifactId")
                        .HasName("pk_calibration_artifacts");

                    b.HasIndex("ContentHash")
                        .IsUnique()
                        .HasDatabaseName("ix_calibration_artifacts_content_hash");

                    b.ToTable("calibration_artifacts", "config");
                });

            modelBuilder.Entity("DBManager.Postgres.Config.DeploymentActivationEventEntity", b =>
                {
                    b.Property<long>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("EventId"));

                    b.Property<string>("ActorIdentity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor_identity");

                    b.Property<Guid>("DeploymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("deployment_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("PolicyRevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("policy_revision_id");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.HasKey("EventId")
                        .HasName("pk_deployment_activation_events");

                    b.HasIndex("DeploymentId", "OccurredAt")
                        .HasDatabaseName("ix_deployment_activation_events_deployment_id_occurred_at");

                    b.ToTable("deployment_activation_events", "config");
                });

            modelBuilder.Entity("DBManager.Postgres.Config.DeploymentAssignmentEntity", b =>
                {
                    b.Property<Guid>("DeploymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("deployment_id");

                    b.Property<long>("InstrumentId")
                        .HasColumnType("bigint")
                        .HasColumnName("instrument_id");

                    b.Property<string>("StrategyId")
                        .HasColumnType("text")
                        .HasColumnName("strategy_id");

                    b.Property<short>("AgentMode")
                        .HasColumnType("smallint")
                        .HasColumnName("agent_mode");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.HasKey("DeploymentId", "InstrumentId", "StrategyId")
                        .HasName("pk_deployment_assignments");

                    b.HasIndex("InstrumentId")
                        .HasDatabaseName("ix_deployment_assignments_instrument_id");

                    b.ToTable("deployment_assignments", "config");
                });

            modelBuilder.Entity("DBManager.Postgres.Config.DeploymentEntity", b =>
                {
                    b.Property<Guid>("DeploymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("deployment_id");

                    b.Property<Guid>("BrokerAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("broker_account_id");

                    b.Property<string>("DeploymentHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("deployment_hash");

                    b.Property<short>("ExecutionMode")
                        .HasColumnType("smallint")
                        .HasColumnName("execution_mode");

                    b.Property<string>("HostInstanceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("host_instance_id");

                    b.Property<Guid>("PolicyRevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("policy_revision_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("started_at");

                    b.Property<string>("StartedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("started_by");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<string>("StopReason")
                        .HasColumnType("text")
                        .HasColumnName("stop_reason");

                    b.Property<DateTimeOffset?>("StoppedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("stopped_at");

                    b.HasKey("DeploymentId")
                        .HasName("pk_deployments");

                    b.HasIndex("BrokerAccountId")
                        .IsUnique()
                        .HasDatabaseName("ix_deployments_one_active_per_account")
                        .HasFilter("status = 0");

                    b.HasIndex("PolicyRevisionId")
                        .HasDatabaseName("ix_deployments_policy_revision_id");

                    b.ToTable("deployments", "config");
                });

            modelBuilder.Entity("DBManager.Postgres.Config.PolicyArtifactEntity", b =>
                {
                    b.Property<Guid>("PolicyRevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("policy_revision_id");

                    b.Property<short>("Role")
                        .HasColumnType("smallint")
                        .HasColumnName("role");

                    b.Property<Guid>("ArtifactId")
                        .HasColumnType("uuid")
                        .HasColumnName("artifact_id");

                    b.HasKey("PolicyRevisionId", "Role")
                        .HasName("pk_policy_artifacts");

                    b.HasIndex("ArtifactId")
                        .HasDatabaseName("ix_policy_artifacts_artifact_id");

                    b.ToTable("policy_artifacts", "config");
                });

            modelBuilder.Entity("DBManager.Postgres.Config.PolicyProfileEntity", b =>
                {
                    b.Property<Guid>("PolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("policy_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("FeatureSchemaHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("feature_schema_hash");

                    b.Property<string>("StrategyId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("strategy_id");

                    b.Property<string>("StrategyVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("strategy_version");

                    b.HasKey("PolicyId")
                        .HasName("pk_policy_profiles");

                    b.ToTable("policy_profiles", "config");
                });

            modelBuilder.Entity("DBManager.Postgres.Config.PolicyPromotionEventEntity", b =>
                {
                    b.Property<long>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("EventId"));

                    b.Property<string>("ActorIdentity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor_identity");

                    b.Property<short>("FromStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("from_status");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("PolicyRevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("policy_revision_id");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<short>("ToStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("to_status");

                    b.HasKey("EventId")
                        .HasName("pk_policy_promotion_events");

                    b.HasIndex("PolicyRevisionId", "OccurredAt")
                        .HasDatabaseName("ix_policy_promotion_events_policy_revision_id_occurred_at");

                    b.ToTable("policy_promotion_events", "config");
                });

            modelBuilder.Entity("DBManager.Postgres.Config.PolicyRevisionEntity", b =>
                {
                    b.Property<Guid>("PolicyRevisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("policy_revision_id");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("approved_at");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("text")
                        .HasColumnName("approved_by");

                    b.Property<string>("ConfigurationHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("configuration_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("PolicyDocumentJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("policy_document");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid")
                        .HasColumnName("policy_id");

                    b.Property<DateTimeOffset?>("RetiredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("retired_at");

                    b.Property<int>("Revision")
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.HasKey("PolicyRevisionId")
                        .HasName("pk_policy_revisions");

                    b.HasIndex("ConfigurationHash")
                        .IsUnique()
                        .HasDatabaseName("ix_policy_revisions_configuration_hash");

                    b.HasIndex("PolicyId", "Revision")
                        .IsUnique()
                        .HasDatabaseName("ix_policy_revisions_policy_id_revision");

                    b.ToTable("policy_revisions", "config");
                });

            modelBuilder.Entity("DBManager.Postgres.Decision.AgentEvaluationEntity", b =>
                {
                    b.Property<long>("EvaluationSequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("evaluation_sequence");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("EvaluationSequence"));

                    b.Property<short>("Action")
                        .HasColumnType("smallint")
                        .HasColumnName("action");

                    b.Property<Guid>("DecisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("decision_id");

                    b.Property<DateTimeOffset>("DecisionTime")
                        .HasColumnType("timestamptz")
                        .HasColumnName("decision_time");

                    b.Property<Guid>("DeploymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("deployment_id");

                    b.Property<string>("DiagnosticsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("diagnostics");

                    b.Property<long>("InstrumentId")
                        .HasColumnType("bigint")
                        .HasColumnName("instrument_id");

                    b.Property<decimal?>("MtfAlignment")
                        .HasColumnType("numeric(18,10)")
                        .HasColumnName("mtf_alignment");

                    b.Property<DateTimeOffset>("PersistedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("persisted_at");

                    b.Property<Guid>("PolicyRevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("policy_revision_id");

                    b.Property<string>("PrimaryReasonCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("primary_reason_code");

                    b.Property<decimal?>("RawConfidence")
                        .HasColumnType("numeric(18,10)")
                        .HasColumnName("raw_confidence");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("received_at");

                    b.Property<short?>("Regime")
                        .HasColumnType("smallint")
                        .HasColumnName("regime");

                    b.Property<long>("SnapshotVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("snapshot_version");

                    b.Property<short>("StateAfter")
                        .HasColumnType("smallint")
                        .HasColumnName("state_after");

                    b.Property<short>("StateBefore")
                        .HasColumnType("smallint")
                        .HasColumnName("state_before");

                    b.Property<string>("StrategyId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("strategy_id");

                    b.Property<short>("TriggerInterval")
                        .HasColumnType("smallint")
                        .HasColumnName("trigger_interval");

                    b.HasKey("EvaluationSequence")
                        .HasName("pk_agent_evaluations");

                    b.HasIndex("DecisionId")
                        .IsUnique()
                        .HasDatabaseName("ix_agent_evaluations_decision_id");

                    b.HasIndex("DecisionTime")
                        .HasDatabaseName("ix_agent_evaluations_decision_time");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("DecisionTime"), "brin");

                    b.HasIndex("PrimaryReasonCode", "DecisionTime")
                        .HasDatabaseName("ix_agent_evaluations_primary_reason_code_decision_time");

                    b.HasIndex("DeploymentId", "StrategyId", "InstrumentId", "DecisionTime")
                        .HasDatabaseName("ix_agent_evaluations_deployment_id_strategy_id_instrument_id_d");

                    b.ToTable("agent_evaluations", "decision");
                });

            modelBuilder.Entity("DBManager.Postgres.Decision.CandidateKeyEntity", b =>
                {
                    b.Property<Guid>("CandidateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_id");

                    b.Property<DateTimeOffset>("CandidateTime")
                        .HasColumnType("timestamptz")
                        .HasColumnName("candidate_time");

                    b.Property<short>("CurrentStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("current_status");

                    b.Property<Guid>("DecisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("decision_id");

                    b.HasKey("CandidateId")
                        .HasName("pk_candidate_keys");

                    b.HasIndex("DecisionId")
                        .IsUnique()
                        .HasDatabaseName("ix_candidate_keys_decision_id");

                    b.ToTable("candidate_keys", "decision");
                });

            modelBuilder.Entity("DBManager.Postgres.Decision.CandidateStageEventEntity", b =>
                {
                    b.Property<long>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("EventId"));

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_id");

                    b.Property<decimal?>("ConfidenceAfter")
                        .HasColumnType("numeric(18,10)")
                        .HasColumnName("confidence_after");

                    b.Property<decimal?>("ConfidenceBefore")
                        .HasColumnType("numeric(18,10)")
                        .HasColumnName("confidence_before");

                    b.Property<string>("DetailsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<short>("Outcome")
                        .HasColumnType("smallint")
                        .HasColumnName("outcome");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason_code");

                    b.Property<decimal?>("RiskMultiplier")
                        .HasColumnType("numeric(18,10)")
                        .HasColumnName("risk_multiplier");

                    b.Property<short>("Stage")
                        .HasColumnType("smallint")
                        .HasColumnName("stage");

                    b.HasKey("EventId")
                        .HasName("pk_candidate_stage_events");

                    b.HasIndex("CandidateId", "OccurredAt")
                        .HasDatabaseName("ix_candidate_stage_events_candidate_id_occurred_at");

                    b.ToTable("candidate_stage_events", "decision");
                });

            modelBuilder.Entity("DBManager.Postgres.Decision.DecisionKeyEntity", b =>
                {
                    b.Property<Guid>("DecisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("decision_id");

                    b.Property<DateTimeOffset>("DecisionTime")
                        .HasColumnType("timestamptz")
                        .HasColumnName("decision_time");

                    b.Property<Guid>("DeploymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("deployment_id");

                    b.HasKey("DecisionId")
                        .HasName("pk_decision_keys");

                    b.ToTable("decision_keys", "decision");
                });

            modelBuilder.Entity("DBManager.Postgres.Decision.TradeCandidateEntity", b =>
                {
                    b.Property<long>("CandidateSequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("candidate_sequence");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("CandidateSequence"));

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DecisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("decision_id");

                    b.Property<DateTimeOffset>("DecisionTime")
                        .HasColumnType("timestamptz")
                        .HasColumnName("decision_time");

                    b.Property<Guid>("DeploymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("deployment_id");

                    b.Property<short>("Direction")
                        .HasColumnType("smallint")
                        .HasColumnName("direction");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<long>("InstrumentId")
                        .HasColumnType("bigint")
                        .HasColumnName("instrument_id");

                    b.Property<string>("MetaLabelAuditJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("meta_label_audit");

                    b.Property<decimal>("MtfAlignment")
                        .HasColumnType("numeric(18,10)")
                        .HasColumnName("mtf_alignment");

                    b.Property<Guid>("PolicyRevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("policy_revision_id");

                    b.Property<decimal>("RawConfidence")
                        .HasColumnType("numeric(18,10)")
                        .HasColumnName("raw_confidence");

                    b.Property<decimal?>("ReferenceAsk")
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("reference_ask");

                    b.Property<decimal?>("ReferenceBid")
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("reference_bid");

                    b.Property<decimal>("ReferenceMid")
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("reference_mid");

                    b.Property<short>("Regime")
                        .HasColumnType("smallint")
                        .HasColumnName("regime");

                    b.Property<string>("SetupCalibrationAuditJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("setup_calibration_audit");

                    b.Property<string>("SetupId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("setup_id");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<decimal>("StopPrice")
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("stop_price");

                    b.Property<string>("StrategyId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("strategy_id");

                    b.Property<decimal?>("TargetPrice")
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("target_price");

                    b.Property<string>("TradingConditionAuditJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("trading_condition_audit");

                    b.HasKey("CandidateSequence")
                        .HasName("pk_trade_candidates");

                    b.HasIndex("CandidateId")
                        .IsUnique()
                        .HasDatabaseName("ix_trade_candidates_candidate_id");

                    b.ToTable("trade_candidates", "decision");
                });

            modelBuilder.Entity("DBManager.Postgres.Execution.BrokerTransactionEntity", b =>
                {
                    b.Property<long>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("EventId"));

                    b.Property<DateTimeOffset?>("AppliedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("applied_at");

                    b.Property<Guid>("BrokerAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("broker_account_id");

                    b.Property<string>("BrokerOrderId")
                        .HasColumnType("text")
                        .HasColumnName("broker_order_id");

                    b.Property<DateTimeOffset>("BrokerTime")
                        .HasColumnType("timestamptz")
                        .HasColumnName("broker_time");

                    b.Property<string>("BrokerTradeId")
                        .HasColumnType("text")
                        .HasColumnName("broker_trade_id");

                    b.Property<string>("BrokerTransactionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("broker_transaction_id");

                    b.Property<string>("ClientOrderId")
                        .HasColumnType("text")
                        .HasColumnName("client_order_id");

                    b.Property<long?>("InstrumentId")
                        .HasColumnType("bigint")
                        .HasColumnName("instrument_id");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("price");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("quantity");

                    b.Property<string>("RawPayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_payload");

                    b.Property<string>("ReasonCode")
                        .HasColumnType("text")
                        .HasColumnName("reason_code");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("received_at");

                    b.Property<short>("TransactionType")
                        .HasColumnType("smallint")
                        .HasColumnName("transaction_type");

                    b.HasKey("EventId")
                        .HasName("pk_broker_transactions");

                    b.ToTable("broker_transactions", "execution");
                });

            modelBuilder.Entity("DBManager.Postgres.Execution.BrokerTransactionKeyEntity", b =>
                {
                    b.Property<Guid>("BrokerAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("broker_account_id");

                    b.Property<string>("BrokerTransactionId")
                        .HasColumnType("text")
                        .HasColumnName("broker_transaction_id");

                    b.Property<DateTimeOffset>("BrokerTime")
                        .HasColumnType("timestamptz")
                        .HasColumnName("broker_time");

                    b.HasKey("BrokerAccountId", "BrokerTransactionId")
                        .HasName("pk_broker_transaction_keys");

                    b.ToTable("broker_transaction_keys", "execution");
                });

            modelBuilder.Entity("DBManager.Postgres.Execution.FillEntity", b =>
                {
                    b.Property<Guid>("FillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("fill_id");

                    b.Property<Guid>("BrokerAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("broker_account_id");

                    b.Property<string>("BrokerFillId")
                        .HasColumnType("text")
                        .HasColumnName("broker_fill_id");

                    b.Property<DateTimeOffset>("BrokerTime")
                        .HasColumnType("timestamptz")
                        .HasColumnName("broker_time");

                    b.Property<string>("BrokerTransactionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("broker_transaction_id");

                    b.Property<decimal>("Commission")
                        .HasColumnType("numeric(28,8)")
                        .HasColumnName("commission");

                    b.Property<decimal>("Financing")
                        .HasColumnType("numeric(28,8)")
                        .HasColumnName("financing");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("price");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("quantity");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("received_at");

                    b.Property<decimal?>("SlippageCost")
                        .HasColumnType("numeric(28,8)")
                        .HasColumnName("slippage_cost");

                    b.Property<decimal?>("SpreadCost")
                        .HasColumnType("numeric(28,8)")
                        .HasColumnName("spread_cost");

                    b.HasKey("FillId")
                        .HasName("pk_fills");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_fills_order_id");

                    b.HasIndex("BrokerAccountId", "BrokerTransactionId")
                        .IsUnique()
                        .HasDatabaseName("ix_fills_broker_account_id_broker_transaction_id");

                    b.ToTable("fills", "execution");
                });

            modelBuilder.Entity("DBManager.Postgres.Execution.OrderCommandEntity", b =>
                {
                    b.Property<Guid>("CommandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("command_id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_id");

                    b.Property<string>("ClientOrderId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("client_order_id");

                    b.Property<short>("CommandType")
                        .HasColumnType("smallint")
                        .HasColumnName("command_type");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<decimal>("RequestedQuantity")
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("requested_quantity");

                    b.Property<decimal?>("RequestedStop")
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("requested_stop");

                    b.Property<decimal?>("RequestedTarget")
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("requested_target");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("reservation_id");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("started_at");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("CommandId")
                        .HasName("pk_order_commands");

                    b.HasIndex("CandidateId")
                        .HasDatabaseName("ix_order_commands_candidate_id");

                    b.HasIndex("ClientOrderId")
                        .IsUnique()
                        .HasDatabaseName("ix_order_commands_client_order_id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_order_commands_idempotency_key");

                    b.ToTable("order_commands", "execution");
                });

            modelBuilder.Entity("DBManager.Postgres.Execution.OrderEntity", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("accepted_at");

                    b.Property<decimal?>("AverageFillPrice")
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("average_fill_price");

                    b.Property<Guid>("BrokerAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("broker_account_id");

                    b.Property<string>("BrokerOrderId")
                        .HasColumnType("text")
                        .HasColumnName("broker_order_id");

                    b.Property<string>("BrokerTradeId")
                        .HasColumnType("text")
                        .HasColumnName("broker_trade_id");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_id");

                    b.Property<string>("ClientOrderId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("client_order_id");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("closed_at");

                    b.Property<Guid>("CommandId")
                        .HasColumnType("uuid")
                        .HasColumnName("command_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<short>("Direction")
                        .HasColumnType("smallint")
                        .HasColumnName("direction");

                    b.Property<DateTimeOffset?>("FilledAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("filled_at");

                    b.Property<decimal>("FilledQuantity")
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("filled_quantity");

                    b.Property<decimal>("InitialStopPrice")
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("initial_stop_price");

                    b.Property<decimal?>("InitialTargetPrice")
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("initial_target_price");

                    b.Property<long>("InstrumentId")
                        .HasColumnType("bigint")
                        .HasColumnName("instrument_id");

                    b.Property<decimal>("RequestedQuantity")
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("requested_quantity");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("reservation_id");

                    b.Property<short>("State")
                        .HasColumnType("smallint")
                        .HasColumnName("state");

                    b.Property<string>("StrategyId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("strategy_id");

                    b.Property<short>("SubmissionCertainty")
                        .HasColumnType("smallint")
                        .HasColumnName("submission_certainty");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("submitted_at");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("OrderId")
                        .HasName("pk_orders");

                    b.HasIndex("ClientOrderId")
                        .IsUnique()
                        .HasDatabaseName("ix_orders_client_order_id");

                    b.HasIndex("CommandId")
                        .IsUnique()
                        .HasDatabaseName("ix_orders_command_id");

                    b.HasIndex("State")
                        .HasDatabaseName("ix_orders_active")
                        .HasFilter("state IN (0,1,2,4,5)");

                    b.HasIndex("BrokerAccountId", "State")
                        .HasDatabaseName("ix_orders_broker_account_id_state");

                    b.HasIndex("InstrumentId", "State")
                        .HasDatabaseName("ix_orders_instrument_id_state");

                    b.HasIndex("StrategyId", "State")
                        .HasDatabaseName("ix_orders_strategy_id_state");

                    b.ToTable("orders", "execution");
                });

            modelBuilder.Entity("DBManager.Postgres.Execution.OrderEventEntity", b =>
                {
                    b.Property<long>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("EventId"));

                    b.Property<string>("BrokerTransactionId")
                        .HasColumnType("text")
                        .HasColumnName("broker_transaction_id");

                    b.Property<string>("DetailsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<short>("EventType")
                        .HasColumnType("smallint")
                        .HasColumnName("event_type");

                    b.Property<short?>("FromState")
                        .HasColumnType("smallint")
                        .HasColumnName("from_state");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("price");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("quantity");

                    b.Property<string>("ReasonCode")
                        .HasColumnType("text")
                        .HasColumnName("reason_code");

                    b.Property<short?>("ToState")
                        .HasColumnType("smallint")
                        .HasColumnName("to_state");

                    b.HasKey("EventId")
                        .HasName("pk_order_events");

                    b.HasIndex("OrderId", "OccurredAt")
                        .HasDatabaseName("ix_order_events_order_id_occurred_at");

                    b.ToTable("order_events", "execution");
                });

            modelBuilder.Entity("DBManager.Postgres.Execution.PositionEntity", b =>
                {
                    b.Property<Guid>("PositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("position_id");

                    b.Property<decimal>("AverageEntryPrice")
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("average_entry_price");

                    b.Property<Guid>("BrokerAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("broker_account_id");

                    b.Property<string>("BrokerTradeId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("broker_trade_id");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("closed_at");

                    b.Property<decimal>("Commission")
                        .HasColumnType("numeric(28,8)")
                        .HasColumnName("commission");

                    b.Property<decimal>("CurrentStopPrice")
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("current_stop_price");

                    b.Property<short>("Direction")
                        .HasColumnType("smallint")
                        .HasColumnName("direction");

                    b.Property<decimal>("Financing")
                        .HasColumnType("numeric(28,8)")
                        .HasColumnName("financing");

                    b.Property<decimal>("InitialStopPrice")
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("initial_stop_price");

                    b.Property<long>("InstrumentId")
                        .HasColumnType("bigint")
                        .HasColumnName("instrument_id");

                    b.Property<Guid?>("ManagementArtifactId")
                        .HasColumnType("uuid")
                        .HasColumnName("management_artifact_id");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("opened_at");

                    b.Property<decimal>("OriginalQuantity")
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("original_quantity");

                    b.Property<decimal>("OriginalRisk")
                        .HasColumnType("numeric(28,8)")
                        .HasColumnName("original_risk");

                    b.Property<Guid>("PolicyRevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("policy_revision_id");

                    b.Property<decimal>("RealisedPnl")
                        .HasColumnType("numeric(28,8)")
                        .HasColumnName("realised_pnl");

                    b.Property<decimal>("RemainingQuantity")
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("remaining_quantity");

                    b.Property<decimal>("RemainingRisk")
                        .HasColumnType("numeric(28,8)")
                        .HasColumnName("remaining_risk");

                    b.Property<short>("State")
                        .HasColumnType("smallint")
                        .HasColumnName("state");

                    b.Property<string>("StrategyId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("strategy_id");

                    b.Property<decimal?>("TargetPrice")
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("target_price");

                    b.Property<decimal>("UnrealisedPnl")
                        .HasColumnType("numeric(28,8)")
                        .HasColumnName("unrealised_pnl");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("PositionId")
                        .HasName("pk_positions");

                    b.HasIndex("PolicyRevisionId")
                        .HasDatabaseName("ix_positions_policy_revision_id");

                    b.HasIndex("BrokerAccountId", "BrokerTradeId", "StrategyId")
                        .IsUnique()
                        .HasDatabaseName("ix_positions_broker_account_id_broker_trade_id_strategy_id");

                    b.ToTable("positions", "execution");
                });

            modelBuilder.Entity("DBManager.Postgres.Execution.PositionEventEntity", b =>
                {
                    b.Property<long>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("EventId"));

                    b.Property<string>("BrokerTransactionId")
                        .HasColumnType("text")
                        .HasColumnName("broker_transaction_id");

                    b.Property<string>("DetailsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<short>("EventType")
                        .HasColumnType("smallint")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid")
                        .HasColumnName("position_id");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("price");

                    b.Property<decimal?>("QuantityDelta")
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("quantity_delta");

                    b.Property<decimal?>("RealisedPnlDelta")
                        .HasColumnType("numeric(28,8)")
                        .HasColumnName("realised_pnl_delta");

                    b.Property<string>("ReasonCode")
                        .HasColumnType("text")
                        .HasColumnName("reason_code");

                    b.HasKey("EventId")
                        .HasName("pk_position_events");

                    b.HasIndex("PositionId", "OccurredAt")
                        .HasDatabaseName("ix_position_events_position_id_occurred_at");

                    b.ToTable("position_events", "execution");
                });

            modelBuilder.Entity("DBManager.Postgres.Operations.BrokerStreamCursorEntity", b =>
                {
                    b.Property<Guid>("BrokerAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("broker_account_id");

                    b.Property<long>("ConnectionGeneration")
                        .HasColumnType("bigint")
                        .HasColumnName("connection_generation");

                    b.Property<DateTimeOffset?>("LastAppliedBrokerTime")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_applied_broker_time");

                    b.Property<string>("LastAppliedTransactionId")
                        .HasColumnType("text")
                        .HasColumnName("last_applied_transaction_id");

                    b.Property<DateTimeOffset?>("LastHeartbeatAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_heartbeat_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("BrokerAccountId")
                        .HasName("pk_broker_stream_cursors");

                    b.ToTable("broker_stream_cursors", "operations");
                });

            modelBuilder.Entity("DBManager.Postgres.Operations.ReconciliationDifferenceEntity", b =>
                {
                    b.Property<Guid>("DifferenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("difference_id");

                    b.Property<short?>("Action")
                        .HasColumnType("smallint")
                        .HasColumnName("action");

                    b.Property<string>("BrokerValueJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("broker_value");

                    b.Property<short>("DifferenceType")
                        .HasColumnType("smallint")
                        .HasColumnName("difference_type");

                    b.Property<long?>("InstrumentId")
                        .HasColumnType("bigint")
                        .HasColumnName("instrument_id");

                    b.Property<string>("LocalValueJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("local_value");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid?>("PositionId")
                        .HasColumnType("uuid")
                        .HasColumnName("position_id");

                    b.Property<Guid>("ReconciliationId")
                        .HasColumnType("uuid")
                        .HasColumnName("reconciliation_id");

                    b.Property<string>("ResolutionNote")
                        .HasColumnType("text")
                        .HasColumnName("resolution_note");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("resolved_at");

                    b.Property<short>("Severity")
                        .HasColumnType("smallint")
                        .HasColumnName("severity");

                    b.HasKey("DifferenceId")
                        .HasName("pk_reconciliation_differences");

                    b.HasIndex("ReconciliationId")
                        .HasDatabaseName("ix_reconciliation_differences_reconciliation_id");

                    b.ToTable("reconciliation_differences", "operations");
                });

            modelBuilder.Entity("DBManager.Postgres.Operations.ReconciliationRunEntity", b =>
                {
                    b.Property<Guid>("ReconciliationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("reconciliation_id");

                    b.Property<Guid>("BrokerAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("broker_account_id");

                    b.Property<DateTimeOffset?>("BrokerSnapshotTime")
                        .HasColumnType("timestamptz")
                        .HasColumnName("broker_snapshot_time");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("completed_at");

                    b.Property<bool>("EntriesPaused")
                        .HasColumnType("boolean")
                        .HasColumnName("entries_paused");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("started_at");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<string>("SummaryJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("summary");

                    b.Property<short>("Trigger")
                        .HasColumnType("smallint")
                        .HasColumnName("trigger");

                    b.HasKey("ReconciliationId")
                        .HasName("pk_reconciliation_runs");

                    b.ToTable("reconciliation_runs", "operations");
                });

            modelBuilder.Entity("DBManager.Postgres.Reference.BrokerAccountEntity", b =>
                {
                    b.Property<Guid>("BrokerAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("broker_account_id");

                    b.Property<string>("AccountCurrency")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("account_currency");

                    b.Property<long>("BrokerId")
                        .HasColumnType("bigint")
                        .HasColumnName("broker_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<short>("Environment")
                        .HasColumnType("smallint")
                        .HasColumnName("environment");

                    b.Property<string>("ExternalAccountKeyHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_account_key_hash");

                    b.Property<string>("MaskedAccountName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("masked_account_name");

                    b.HasKey("BrokerAccountId")
                        .HasName("pk_broker_accounts");

                    b.HasIndex("BrokerId")
                        .HasDatabaseName("ix_broker_accounts_broker_id");

                    b.ToTable("broker_accounts", "reference");
                });

            modelBuilder.Entity("DBManager.Postgres.Reference.BrokerEntity", b =>
                {
                    b.Property<long>("BrokerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("broker_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("BrokerId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.HasKey("BrokerId")
                        .HasName("pk_brokers");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_brokers_code");

                    b.ToTable("brokers", "reference");
                });

            modelBuilder.Entity("DBManager.Postgres.Reference.BrokerInstrumentEntity", b =>
                {
                    b.Property<Guid>("BrokerAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("broker_account_id");

                    b.Property<long>("InstrumentId")
                        .HasColumnType("bigint")
                        .HasColumnName("instrument_id");

                    b.Property<long>("MetadataRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("metadata_revision");

                    b.Property<string>("BrokerSymbol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("broker_symbol");

                    b.Property<decimal>("MarginRate")
                        .HasColumnType("numeric(18,10)")
                        .HasColumnName("margin_rate");

                    b.Property<decimal?>("MaximumQuantity")
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("maximum_quantity");

                    b.Property<decimal>("MinimumQuantity")
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("minimum_quantity");

                    b.Property<short?>("PipLocation")
                        .HasColumnType("smallint")
                        .HasColumnName("pip_location");

                    b.Property<short>("PricePrecision")
                        .HasColumnType("smallint")
                        .HasColumnName("price_precision");

                    b.Property<short>("QuantityPrecision")
                        .HasColumnType("smallint")
                        .HasColumnName("quantity_precision");

                    b.Property<decimal>("QuantityStep")
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("quantity_step");

                    b.Property<bool>("Tradeable")
                        .HasColumnType("boolean")
                        .HasColumnName("tradeable");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("timestamptz")
                        .HasColumnName("valid_from");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("timestamptz")
                        .HasColumnName("valid_to");

                    b.HasKey("BrokerAccountId", "InstrumentId", "MetadataRevision")
                        .HasName("pk_broker_instruments");

                    b.HasIndex("InstrumentId")
                        .HasDatabaseName("ix_broker_instruments_instrument_id");

                    b.ToTable("broker_instruments", "reference");
                });

            modelBuilder.Entity("DBManager.Postgres.Reference.InstrumentEntity", b =>
                {
                    b.Property<long>("InstrumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("instrument_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("InstrumentId"));

                    b.Property<short>("AssetClass")
                        .HasColumnType("smallint")
                        .HasColumnName("asset_class");

                    b.Property<string>("BaseCurrency")
                        .HasColumnType("char(3)")
                        .HasColumnName("base_currency");

                    b.Property<string>("CanonicalKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("canonical_key");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("QuoteCurrency")
                        .HasColumnType("char(3)")
                        .HasColumnName("quote_currency");

                    b.HasKey("InstrumentId")
                        .HasName("pk_instruments");

                    b.HasIndex("CanonicalKey")
                        .IsUnique()
                        .HasDatabaseName("ix_instruments_canonical_key");

                    b.ToTable("instruments", "reference");
                });

            modelBuilder.Entity("DBManager.Postgres.Risk.PortfolioDecisionEntity", b =>
                {
                    b.Property<Guid>("PortfolioDecisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("portfolio_decision_id");

                    b.Property<bool>("Approved")
                        .HasColumnType("boolean")
                        .HasColumnName("approved");

                    b.Property<decimal>("ApprovedQuantity")
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("approved_quantity");

                    b.Property<decimal>("ApprovedRisk")
                        .HasColumnType("numeric(28,8)")
                        .HasColumnName("approved_risk");

                    b.Property<Guid>("BrokerAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("broker_account_id");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("DecisionEpoch")
                        .HasColumnType("timestamptz")
                        .HasColumnName("decision_epoch");

                    b.Property<decimal>("EstimatedMargin")
                        .HasColumnType("numeric(28,8)")
                        .HasColumnName("estimated_margin");

                    b.Property<string>("PortfolioSnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("portfolio_snapshot");

                    b.Property<int>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason_code");

                    b.Property<decimal>("RequestedQuantity")
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("requested_quantity");

                    b.Property<decimal>("RequestedRisk")
                        .HasColumnType("numeric(28,8)")
                        .HasColumnName("requested_risk");

                    b.HasKey("PortfolioDecisionId")
                        .HasName("pk_portfolio_decisions");

                    b.HasIndex("CandidateId")
                        .IsUnique()
                        .HasDatabaseName("ix_portfolio_decisions_candidate_id");

                    b.ToTable("portfolio_decisions", "risk");
                });

            modelBuilder.Entity("DBManager.Postgres.Risk.PositionSizingEvaluationEntity", b =>
                {
                    b.Property<Guid>("SizingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("sizing_id");

                    b.Property<long>("AccountSnapshotVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("account_snapshot_version");

                    b.Property<bool>("Approved")
                        .HasColumnType("boolean")
                        .HasColumnName("approved");

                    b.Property<string>("AuditJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("audit");

                    b.Property<decimal>("BaseRiskAmount")
                        .HasColumnType("numeric(28,8)")
                        .HasColumnName("base_risk_amount");

                    b.Property<Guid>("BrokerAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("broker_account_id");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_id");

                    b.Property<string>("ConversionPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("conversion_path");

                    b.Property<decimal>("ConversionRate")
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("conversion_rate");

                    b.Property<decimal>("Equity")
                        .HasColumnType("numeric(28,8)")
                        .HasColumnName("equity");

                    b.Property<decimal>("EstimatedMargin")
                        .HasColumnType("numeric(28,8)")
                        .HasColumnName("estimated_margin");

                    b.Property<decimal>("EstimatedStopLoss")
                        .HasColumnType("numeric(28,8)")
                        .HasColumnName("estimated_stop_loss");

                    b.Property<DateTimeOffset>("EvaluatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("evaluated_at");

                    b.Property<decimal>("ExpectedCommission")
                        .HasColumnType("numeric(28,8)")
                        .HasColumnName("expected_commission");

                    b.Property<decimal>("ExpectedSlippage")
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("expected_slippage");

                    b.Property<decimal>("ExpectedSpread")
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("expected_spread");

                    b.Property<long>("InstrumentMetadataRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("instrument_metadata_revision");

                    b.Property<decimal>("NormalizedQuantity")
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("normalized_quantity");

                    b.Property<decimal>("RawQuantity")
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("raw_quantity");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason_code");

                    b.Property<decimal>("StopDistance")
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("stop_distance");

                    b.HasKey("SizingId")
                        .HasName("pk_position_sizing_evaluations");

                    b.HasIndex("CandidateId")
                        .IsUnique()
                        .HasDatabaseName("ix_position_sizing_evaluations_candidate_id");

                    b.ToTable("position_sizing_evaluations", "risk");
                });

            modelBuilder.Entity("DBManager.Postgres.Risk.ReservationEntity", b =>
                {
                    b.Property<Guid>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("reservation_id");

                    b.Property<Guid>("BrokerAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("broker_account_id");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("PortfolioDecisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("portfolio_decision_id");

                    b.Property<decimal>("ReservedMargin")
                        .HasColumnType("numeric(28,8)")
                        .HasColumnName("reserved_margin");

                    b.Property<decimal>("ReservedQuantity")
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("reserved_quantity");

                    b.Property<decimal>("ReservedRisk")
                        .HasColumnType("numeric(28,8)")
                        .HasColumnName("reserved_risk");

                    b.Property<short>("State")
                        .HasColumnType("smallint")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("ReservationId")
                        .HasName("pk_reservations");

                    b.HasIndex("BrokerAccountId")
                        .HasDatabaseName("ix_reservations_active_by_account")
                        .HasFilter("state IN (0,1,2,3)");

                    b.HasIndex("CandidateId")
                        .IsUnique()
                        .HasDatabaseName("ix_reservations_candidate_id");

                    b.HasIndex("PortfolioDecisionId")
                        .IsUnique()
                        .HasDatabaseName("ix_reservations_portfolio_decision_id");

                    b.HasIndex("BrokerAccountId", "State", "ExpiresAt")
                        .HasDatabaseName("ix_reservations_broker_account_id_state_expires_at");

                    b.ToTable("reservations", "risk");
                });

            modelBuilder.Entity("DBManager.Postgres.Risk.ReservationEventEntity", b =>
                {
                    b.Property<long>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("EventId"));

                    b.Property<string>("DetailsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<short>("FromState")
                        .HasColumnType("smallint")
                        .HasColumnName("from_state");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason_code");

                    b.Property<Guid?>("RelatedOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_order_id");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("reservation_id");

                    b.Property<short>("ToState")
                        .HasColumnType("smallint")
                        .HasColumnName("to_state");

                    b.HasKey("EventId")
                        .HasName("pk_reservation_events");

                    b.HasIndex("ReservationId", "OccurredAt")
                        .HasDatabaseName("ix_reservation_events_reservation_id_occurred_at");

                    b.ToTable("reservation_events", "risk");
                });

            modelBuilder.Entity("DBManager.Postgres.Config.DeploymentAssignmentEntity", b =>
                {
                    b.HasOne("DBManager.Postgres.Config.DeploymentEntity", null)
                        .WithMany()
                        .HasForeignKey("DeploymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_deployment_assignments_deployments_deployment_id");

                    b.HasOne("DBManager.Postgres.Reference.InstrumentEntity", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_deployment_assignments_instruments_instrument_id");
                });

            modelBuilder.Entity("DBManager.Postgres.Config.DeploymentEntity", b =>
                {
                    b.HasOne("DBManager.Postgres.Reference.BrokerAccountEntity", null)
                        .WithMany()
                        .HasForeignKey("BrokerAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_deployments_broker_accounts_broker_account_id");

                    b.HasOne("DBManager.Postgres.Config.PolicyRevisionEntity", null)
                        .WithMany()
                        .HasForeignKey("PolicyRevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_deployments_policy_revisions_policy_revision_id");
                });

            modelBuilder.Entity("DBManager.Postgres.Config.PolicyArtifactEntity", b =>
                {
                    b.HasOne("DBManager.Postgres.Config.CalibrationArtifactEntity", null)
                        .WithMany()
                        .HasForeignKey("ArtifactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_policy_artifacts_calibration_artifacts_artifact_id");

                    b.HasOne("DBManager.Postgres.Config.PolicyRevisionEntity", null)
                        .WithMany()
                        .HasForeignKey("PolicyRevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_policy_artifacts_policy_revisions_policy_revision_id");
                });

            modelBuilder.Entity("DBManager.Postgres.Config.PolicyRevisionEntity", b =>
                {
                    b.HasOne("DBManager.Postgres.Config.PolicyProfileEntity", null)
                        .WithMany()
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_policy_revisions_policy_profiles_policy_id");
                });

            modelBuilder.Entity("DBManager.Postgres.Execution.FillEntity", b =>
                {
                    b.HasOne("DBManager.Postgres.Execution.OrderEntity", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_fills_orders_order_id");
                });

            modelBuilder.Entity("DBManager.Postgres.Execution.OrderCommandEntity", b =>
                {
                    b.HasOne("DBManager.Postgres.Decision.CandidateKeyEntity", null)
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_order_commands_candidate_keys_candidate_id");
                });

            modelBuilder.Entity("DBManager.Postgres.Execution.OrderEntity", b =>
                {
                    b.HasOne("DBManager.Postgres.Execution.OrderCommandEntity", null)
                        .WithMany()
                        .HasForeignKey("CommandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_orders_order_commands_command_id");
                });

            modelBuilder.Entity("DBManager.Postgres.Execution.PositionEntity", b =>
                {
                    b.HasOne("DBManager.Postgres.Config.PolicyRevisionEntity", null)
                        .WithMany()
                        .HasForeignKey("PolicyRevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_positions_policy_revisions_policy_revision_id");
                });

            modelBuilder.Entity("DBManager.Postgres.Operations.ReconciliationDifferenceEntity", b =>
                {
                    b.HasOne("DBManager.Postgres.Operations.ReconciliationRunEntity", null)
                        .WithMany()
                        .HasForeignKey("ReconciliationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reconciliation_differences_reconciliation_runs_reconciliati");
                });

            modelBuilder.Entity("DBManager.Postgres.Reference.BrokerAccountEntity", b =>
                {
                    b.HasOne("DBManager.Postgres.Reference.BrokerEntity", null)
                        .WithMany()
                        .HasForeignKey("BrokerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_broker_accounts_brokers_broker_id");
                });

            modelBuilder.Entity("DBManager.Postgres.Reference.BrokerInstrumentEntity", b =>
                {
                    b.HasOne("DBManager.Postgres.Reference.BrokerAccountEntity", null)
                        .WithMany()
                        .HasForeignKey("BrokerAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_broker_instruments_broker_accounts_broker_account_id");

                    b.HasOne("DBManager.Postgres.Reference.InstrumentEntity", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_broker_instruments_instruments_instrument_id");
                });

            modelBuilder.Entity("DBManager.Postgres.Risk.PortfolioDecisionEntity", b =>
                {
                    b.HasOne("DBManager.Postgres.Decision.CandidateKeyEntity", null)
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_portfolio_decisions_candidate_keys_candidate_id");
                });

            modelBuilder.Entity("DBManager.Postgres.Risk.PositionSizingEvaluationEntity", b =>
                {
                    b.HasOne("DBManager.Postgres.Decision.CandidateKeyEntity", null)
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_position_sizing_evaluations_candidate_keys_candidate_id");
                });

            modelBuilder.Entity("DBManager.Postgres.Risk.ReservationEntity", b =>
                {
                    b.HasOne("DBManager.Postgres.Decision.CandidateKeyEntity", null)
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reservations_candidate_keys_candidate_id");

                    b.HasOne("DBManager.Postgres.Risk.PortfolioDecisionEntity", null)
                        .WithMany()
                        .HasForeignKey("PortfolioDecisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reservations_portfolio_decisions_portfolio_decision_id");
                });
#pragma warning restore 612, 618
        }
    }
}
