// <auto-generated />
using System;
using DBManager.Postgres;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DBManager.Postgres.Migrations
{
    [DbContext(typeof(TradingHubDbContext))]
    [Migration("20260718024507_Phase1ReferenceAndConfig")]
    partial class Phase1ReferenceAndConfig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DBManager.Postgres.Config.CalibrationArtifactEntity", b =>
                {
                    b.Property<Guid>("ArtifactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("artifact_id");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("approved_at");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("text")
                        .HasColumnName("approved_by");

                    b.Property<short>("ArtifactType")
                        .HasColumnType("smallint")
                        .HasColumnName("artifact_type");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("FeatureSchemaHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("feature_schema_hash");

                    b.Property<string>("MetricsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metrics");

                    b.Property<long>("SampleCount")
                        .HasColumnType("bigint")
                        .HasColumnName("sample_count");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<string>("StorageUri")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_uri");

                    b.Property<string>("StrategyId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("strategy_id");

                    b.Property<string>("StrategyVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("strategy_version");

                    b.Property<DateTimeOffset?>("TestFrom")
                        .HasColumnType("timestamptz")
                        .HasColumnName("test_from");

                    b.Property<DateTimeOffset?>("TestTo")
                        .HasColumnType("timestamptz")
                        .HasColumnName("test_to");

                    b.Property<DateTimeOffset>("TrainingFrom")
                        .HasColumnType("timestamptz")
                        .HasColumnName("training_from");

                    b.Property<DateTimeOffset>("TrainingTo")
                        .HasColumnType("timestamptz")
                        .HasColumnName("training_to");

                    b.Property<DateTimeOffset>("ValidationFrom")
                        .HasColumnType("timestamptz")
                        .HasColumnName("validation_from");

                    b.Property<DateTimeOffset>("ValidationTo")
                        .HasColumnType("timestamptz")
                        .HasColumnName("validation_to");

                    b.HasKey("ArtifactId")
                        .HasName("pk_calibration_artifacts");

                    b.HasIndex("ContentHash")
                        .IsUnique()
                        .HasDatabaseName("ix_calibration_artifacts_content_hash");

                    b.ToTable("calibration_artifacts", "config");
                });

            modelBuilder.Entity("DBManager.Postgres.Config.DeploymentActivationEventEntity", b =>
                {
                    b.Property<long>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("EventId"));

                    b.Property<string>("ActorIdentity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor_identity");

                    b.Property<Guid>("DeploymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("deployment_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("PolicyRevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("policy_revision_id");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.HasKey("EventId")
                        .HasName("pk_deployment_activation_events");

                    b.HasIndex("DeploymentId", "OccurredAt")
                        .HasDatabaseName("ix_deployment_activation_events_deployment_id_occurred_at");

                    b.ToTable("deployment_activation_events", "config");
                });

            modelBuilder.Entity("DBManager.Postgres.Config.DeploymentAssignmentEntity", b =>
                {
                    b.Property<Guid>("DeploymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("deployment_id");

                    b.Property<long>("InstrumentId")
                        .HasColumnType("bigint")
                        .HasColumnName("instrument_id");

                    b.Property<string>("StrategyId")
                        .HasColumnType("text")
                        .HasColumnName("strategy_id");

                    b.Property<short>("AgentMode")
                        .HasColumnType("smallint")
                        .HasColumnName("agent_mode");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.HasKey("DeploymentId", "InstrumentId", "StrategyId")
                        .HasName("pk_deployment_assignments");

                    b.HasIndex("InstrumentId")
                        .HasDatabaseName("ix_deployment_assignments_instrument_id");

                    b.ToTable("deployment_assignments", "config");
                });

            modelBuilder.Entity("DBManager.Postgres.Config.DeploymentEntity", b =>
                {
                    b.Property<Guid>("DeploymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("deployment_id");

                    b.Property<Guid>("BrokerAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("broker_account_id");

                    b.Property<string>("DeploymentHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("deployment_hash");

                    b.Property<short>("ExecutionMode")
                        .HasColumnType("smallint")
                        .HasColumnName("execution_mode");

                    b.Property<string>("HostInstanceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("host_instance_id");

                    b.Property<Guid>("PolicyRevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("policy_revision_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("started_at");

                    b.Property<string>("StartedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("started_by");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<string>("StopReason")
                        .HasColumnType("text")
                        .HasColumnName("stop_reason");

                    b.Property<DateTimeOffset?>("StoppedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("stopped_at");

                    b.HasKey("DeploymentId")
                        .HasName("pk_deployments");

                    b.HasIndex("BrokerAccountId")
                        .IsUnique()
                        .HasDatabaseName("ix_deployments_one_active_per_account")
                        .HasFilter("status = 0");

                    b.HasIndex("PolicyRevisionId")
                        .HasDatabaseName("ix_deployments_policy_revision_id");

                    b.ToTable("deployments", "config");
                });

            modelBuilder.Entity("DBManager.Postgres.Config.PolicyArtifactEntity", b =>
                {
                    b.Property<Guid>("PolicyRevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("policy_revision_id");

                    b.Property<short>("Role")
                        .HasColumnType("smallint")
                        .HasColumnName("role");

                    b.Property<Guid>("ArtifactId")
                        .HasColumnType("uuid")
                        .HasColumnName("artifact_id");

                    b.HasKey("PolicyRevisionId", "Role")
                        .HasName("pk_policy_artifacts");

                    b.HasIndex("ArtifactId")
                        .HasDatabaseName("ix_policy_artifacts_artifact_id");

                    b.ToTable("policy_artifacts", "config");
                });

            modelBuilder.Entity("DBManager.Postgres.Config.PolicyProfileEntity", b =>
                {
                    b.Property<Guid>("PolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("policy_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("FeatureSchemaHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("feature_schema_hash");

                    b.Property<string>("StrategyId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("strategy_id");

                    b.Property<string>("StrategyVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("strategy_version");

                    b.HasKey("PolicyId")
                        .HasName("pk_policy_profiles");

                    b.ToTable("policy_profiles", "config");
                });

            modelBuilder.Entity("DBManager.Postgres.Config.PolicyPromotionEventEntity", b =>
                {
                    b.Property<long>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("EventId"));

                    b.Property<string>("ActorIdentity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor_identity");

                    b.Property<short>("FromStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("from_status");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("PolicyRevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("policy_revision_id");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<short>("ToStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("to_status");

                    b.HasKey("EventId")
                        .HasName("pk_policy_promotion_events");

                    b.HasIndex("PolicyRevisionId", "OccurredAt")
                        .HasDatabaseName("ix_policy_promotion_events_policy_revision_id_occurred_at");

                    b.ToTable("policy_promotion_events", "config");
                });

            modelBuilder.Entity("DBManager.Postgres.Config.PolicyRevisionEntity", b =>
                {
                    b.Property<Guid>("PolicyRevisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("policy_revision_id");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("approved_at");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("text")
                        .HasColumnName("approved_by");

                    b.Property<string>("ConfigurationHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("configuration_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("PolicyDocumentJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("policy_document");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid")
                        .HasColumnName("policy_id");

                    b.Property<DateTimeOffset?>("RetiredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("retired_at");

                    b.Property<int>("Revision")
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.HasKey("PolicyRevisionId")
                        .HasName("pk_policy_revisions");

                    b.HasIndex("ConfigurationHash")
                        .IsUnique()
                        .HasDatabaseName("ix_policy_revisions_configuration_hash");

                    b.HasIndex("PolicyId", "Revision")
                        .IsUnique()
                        .HasDatabaseName("ix_policy_revisions_policy_id_revision");

                    b.ToTable("policy_revisions", "config");
                });

            modelBuilder.Entity("DBManager.Postgres.Reference.BrokerAccountEntity", b =>
                {
                    b.Property<Guid>("BrokerAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("broker_account_id");

                    b.Property<string>("AccountCurrency")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("account_currency");

                    b.Property<long>("BrokerId")
                        .HasColumnType("bigint")
                        .HasColumnName("broker_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<short>("Environment")
                        .HasColumnType("smallint")
                        .HasColumnName("environment");

                    b.Property<string>("ExternalAccountKeyHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_account_key_hash");

                    b.Property<string>("MaskedAccountName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("masked_account_name");

                    b.HasKey("BrokerAccountId")
                        .HasName("pk_broker_accounts");

                    b.HasIndex("BrokerId")
                        .HasDatabaseName("ix_broker_accounts_broker_id");

                    b.ToTable("broker_accounts", "reference");
                });

            modelBuilder.Entity("DBManager.Postgres.Reference.BrokerEntity", b =>
                {
                    b.Property<long>("BrokerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("broker_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("BrokerId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.HasKey("BrokerId")
                        .HasName("pk_brokers");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_brokers_code");

                    b.ToTable("brokers", "reference");
                });

            modelBuilder.Entity("DBManager.Postgres.Reference.BrokerInstrumentEntity", b =>
                {
                    b.Property<Guid>("BrokerAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("broker_account_id");

                    b.Property<long>("InstrumentId")
                        .HasColumnType("bigint")
                        .HasColumnName("instrument_id");

                    b.Property<long>("MetadataRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("metadata_revision");

                    b.Property<string>("BrokerSymbol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("broker_symbol");

                    b.Property<decimal>("MarginRate")
                        .HasColumnType("numeric(18,10)")
                        .HasColumnName("margin_rate");

                    b.Property<decimal?>("MaximumQuantity")
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("maximum_quantity");

                    b.Property<decimal>("MinimumQuantity")
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("minimum_quantity");

                    b.Property<short?>("PipLocation")
                        .HasColumnType("smallint")
                        .HasColumnName("pip_location");

                    b.Property<short>("PricePrecision")
                        .HasColumnType("smallint")
                        .HasColumnName("price_precision");

                    b.Property<short>("QuantityPrecision")
                        .HasColumnType("smallint")
                        .HasColumnName("quantity_precision");

                    b.Property<decimal>("QuantityStep")
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("quantity_step");

                    b.Property<bool>("Tradeable")
                        .HasColumnType("boolean")
                        .HasColumnName("tradeable");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("timestamptz")
                        .HasColumnName("valid_from");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("timestamptz")
                        .HasColumnName("valid_to");

                    b.HasKey("BrokerAccountId", "InstrumentId", "MetadataRevision")
                        .HasName("pk_broker_instruments");

                    b.HasIndex("InstrumentId")
                        .HasDatabaseName("ix_broker_instruments_instrument_id");

                    b.ToTable("broker_instruments", "reference");
                });

            modelBuilder.Entity("DBManager.Postgres.Reference.InstrumentEntity", b =>
                {
                    b.Property<long>("InstrumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("instrument_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("InstrumentId"));

                    b.Property<short>("AssetClass")
                        .HasColumnType("smallint")
                        .HasColumnName("asset_class");

                    b.Property<string>("BaseCurrency")
                        .HasColumnType("char(3)")
                        .HasColumnName("base_currency");

                    b.Property<string>("CanonicalKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("canonical_key");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("QuoteCurrency")
                        .HasColumnType("char(3)")
                        .HasColumnName("quote_currency");

                    b.HasKey("InstrumentId")
                        .HasName("pk_instruments");

                    b.HasIndex("CanonicalKey")
                        .IsUnique()
                        .HasDatabaseName("ix_instruments_canonical_key");

                    b.ToTable("instruments", "reference");
                });

            modelBuilder.Entity("DBManager.Postgres.Config.DeploymentAssignmentEntity", b =>
                {
                    b.HasOne("DBManager.Postgres.Config.DeploymentEntity", null)
                        .WithMany()
                        .HasForeignKey("DeploymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_deployment_assignments_deployments_deployment_id");

                    b.HasOne("DBManager.Postgres.Reference.InstrumentEntity", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_deployment_assignments_instruments_instrument_id");
                });

            modelBuilder.Entity("DBManager.Postgres.Config.DeploymentEntity", b =>
                {
                    b.HasOne("DBManager.Postgres.Reference.BrokerAccountEntity", null)
                        .WithMany()
                        .HasForeignKey("BrokerAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_deployments_broker_accounts_broker_account_id");

                    b.HasOne("DBManager.Postgres.Config.PolicyRevisionEntity", null)
                        .WithMany()
                        .HasForeignKey("PolicyRevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_deployments_policy_revisions_policy_revision_id");
                });

            modelBuilder.Entity("DBManager.Postgres.Config.PolicyArtifactEntity", b =>
                {
                    b.HasOne("DBManager.Postgres.Config.CalibrationArtifactEntity", null)
                        .WithMany()
                        .HasForeignKey("ArtifactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_policy_artifacts_calibration_artifacts_artifact_id");

                    b.HasOne("DBManager.Postgres.Config.PolicyRevisionEntity", null)
                        .WithMany()
                        .HasForeignKey("PolicyRevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_policy_artifacts_policy_revisions_policy_revision_id");
                });

            modelBuilder.Entity("DBManager.Postgres.Config.PolicyRevisionEntity", b =>
                {
                    b.HasOne("DBManager.Postgres.Config.PolicyProfileEntity", null)
                        .WithMany()
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_policy_revisions_policy_profiles_policy_id");
                });

            modelBuilder.Entity("DBManager.Postgres.Reference.BrokerAccountEntity", b =>
                {
                    b.HasOne("DBManager.Postgres.Reference.BrokerEntity", null)
                        .WithMany()
                        .HasForeignKey("BrokerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_broker_accounts_brokers_broker_id");
                });

            modelBuilder.Entity("DBManager.Postgres.Reference.BrokerInstrumentEntity", b =>
                {
                    b.HasOne("DBManager.Postgres.Reference.BrokerAccountEntity", null)
                        .WithMany()
                        .HasForeignKey("BrokerAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_broker_instruments_broker_accounts_broker_account_id");

                    b.HasOne("DBManager.Postgres.Reference.InstrumentEntity", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_broker_instruments_instruments_instrument_id");
                });
#pragma warning restore 612, 618
        }
    }
}
